name: 'Ngrok TCP Tunelling'
description: 'A github action for tunelling TCP traffic from within Workflow enviroment'

branding:
  icon: 'activity'  
  color: 'green'

inputs:
  timeout:  
    description: 'Challenge deployment timeout'
    required: true
    default: '1h'
  port:
    description: 'The port to forward traffic to'
    required: true
  ngrok_authtoken:
    description: 'Ngrok authorization token'
    required: true
  os:
    description: 'Operating system'
    required: true

runs:
  using: "composite"
  steps: 
    - run: ./download.sh ${{ inputs.os }}
      shell: bash
    - run: unzip -qq ngrok.zip
      shell: bash
    - run: ./ngrok authtoken ${{ inputs.ngrok_authtoken }}
      shell: bash
    - run: timeout ${{ inputs.timeout }} ./ngrok tcp ${{ inputs.port }}
      shell: bash